# Generated by Django 4.2.6 on 2023-11-06 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curdapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='employees',
            new_name='employees1',
        ),
    ]
