# Generated by Django 4.2.6 on 2023-10-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('mailid', models.EmailField(max_length=254)),
                ('phn', models.IntegerField()),
                ('destination', models.CharField(max_length=10)),
            ],
        ),
    ]
