# Generated by Django 4.2.6 on 2023-11-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0003_registertable'),
    ]

    operations = [
        migrations.CreateModel(
            name='databasedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=10)),
                ('lastname', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('adress', models.CharField(max_length=5)),
                ('password', models.CharField(max_length=10)),
                ('confirmpassword', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='registertable',
            name='adress',
            field=models.CharField(max_length=5),
        ),
    ]
